# Site settings
title: Furry Logic Book
email: mail@kdurrani.co.uk
description: > # this means to ignore newlines until "baseurl:"
 Furry Logic, a book about animal physics, is out from 6 October 2016. From heat and light to electricity and magnetism, Furry Logic unveils the ways that animals exploit physics to eat, drink, mate and dodge death in their daily battle for survival.
url: "http://furrylogicbook.com" # the base hostname & protocol for your site - used for feed.xml
twitter_username: kdurrani
github_username:  katjad

# Build settings
markdown: kramdown