---
title: Furry Logic Book
timezone: UTC
collections:
  chapters:
    title: Chapters
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: mail@kdurrani.co.uk
description: Furry Logic, a book about animal physics, is out from 6 October 2016.
  From heat and light to electricity and magnetism, Furry Logic unveils the ways that
  animals exploit physics to eat, drink, mate and dodge death in their daily battle
  for survival.
url: http://furrylogicbook.com
twitter_username: kdurrani
github_username: katjad
markdown: kramdown
